pipeline{
    agent any
    options {
        ansiColor('xterm')
    }
    
    stages{
        stage("Build API AMI"){
            steps{
                    sh '''#!/bin/bash
                    cd nodejs-aws-jenkins-terraform/terraform
                    ARTIFACT_API=`packer build -machine-readable packer-ami-api.json  |awk -F, '$0 ~/artifact,0,id/ {print $6}'` --output json
                    AMI_ID_API=`echo $ARTIFACT_API | cut -d ':' -f2`
                    echo 'variable "API_INSTANCE_AMI" { default = "'${AMI_ID_API}'" }' > amivar_API.tf
                    aws s3 cp amivar_API.tf s3://cicd-node-aws-jenkins-terraform/amivar_api.tf
                    '''
            }
        }
    
        stage("Build WEB AMI"){
            steps{
                    sh '''#!/bin/bash
                    cd nodejs-aws-jenkins-terraform/terraform
                    ARTIFACT_WEB=`packer build -machine-readable packer-ami-web.json  |awk -F, '$0 ~/artifact,0,id/ {print $6}'` --output json
                    AMI_ID_WEB=`echo $ARTIFACT_WEB | cut -d ':' -f2`
                    echo 'variable "WEB_INSTANCE_AMI" { default = "'${AMI_ID_WEB}'" }' > amivar_web.tf
                    aws s3 cp amivar_web.tf s3://cicd-node-aws-jenkins-terraform/amivar_web.tf
                    '''
        }
        }
    }
}
